language: python
dist: xenial
matrix:
  include:
  - python: '3.6'
    env: NOXSESSION="tests-3.6"
  - python: '3.7'
    env: NOXSESSION="tests-3.7"
  - python: '3.8'
    env: NOXSESSION="tests-3.8"
  - python: '3.8'
    env: NOXSESSION="lint"
install:
- pip install nox
script: nox --session "$NOXSESSION"

after_success:
  - pip install coveralls
  - coveralls

# Assuming you have installed the travis-ci CLI tool, after you
# create the GitHub repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  - provider: pages
    skip_cleanup: true
    keep_history: true
    github_token:
        secure: 0AQmuFenvCEwkWT2rZfLbEu6CSO1yqef1gd3yyKsrv1OCx+wKXSyKWNu1lWAmzbk0xibyi7JbqRJHLnbzUpxAj/j2NeP7N0wm130rPfSpEwrRIpwLHp2eNTll3YgfgcSTYBHSWXiAesuHhjegUixBe3fEojD/SO8Vwa0zZYsFHAlrPRJTnBLW3Yl5FGaTj3F9PG0VOPNI1qlgaMHPTmpqESddh4vKHzKhem4fne6oU0FOEjsy9mijdxdS4OH7bA1ixnN5NWrKSOepp59tBSwVNoiLP58ZTVCQcnYlGK3DBfPbSB1ZltEc0vRdH8fk8aOXxDtBc/WfbUrJ6gav5NPk4VfLs5swAEw9e+6vm06B5i5hg6xCNgcSlMvqtsYwDLKldcQUopDQ6IHZICRHCGPZWZB0nnGRgWKKhPG8wT1rFwt0tH62ruz36PK/7bTceB3mML94d750Zu8c4pbIHmD5s1KJFIXm4v8ML+Gr7xNAebukNkBeSazsXl1dr8g1AIy1MTTQC+bcBIaXJ7tjauRA26xbhoHPtE+VS5BQSOZ1RihcDzPEe9azym3iX7snvCJ4r4CqbUt/Jjb5v939UYEC5XnceKMZG62VSBSmuRKdiVY5a+G/S+oj/Wzcglb3C5YiS6lJMH5EESRVYVkZG4CSHWm7GGLoOEKI9piyKKwL74=
    on:
      tags: true
      branch: master
      python: 3.8
    local-dir: docs/_build/html

  - provider: pypi
    skip_cleanup: true
    distributions: sdist bdist_wheel
    user: __token__
    password:
        secure: "WF9apZHztLe8VjSF4t3lz9NmWfVOZl8082HXIm64MDj8QIhpFuQLBw9cMpZVf1nBXyuanJBwy5FTSXQxEYfqZSrzMkp5tb2S2JwygYYC1xfIILCRawJepWShsR8MCnS0YT12kgZ7esqVxjxjXN7oKrnF0DHHyNpsoNV/pY97L8J4a/Fs1Z1lwhUuotCE2EhK2jDNvl2jKofxmsf9oiTH5gtMHa8yfaRZURye3wjxDbtXK88qH1wxjUi1i0UGjnrzbpwP17CTggK0CjKj248oq7cRcPRC6Vj/NOfa1rLjrkIgY3PDVe2k/7wBuu0FM8VAoHIElGd4y0qwDg4lLn0gv0T3LWM7zzoOx+Uu8AXIu67p0ADV/bJzWL0jaTHBq7J7q6a1zMNCq550mr5m/phgIMr8JH9XwzvTFXsBMokxe1L9WDQ0B/pUFb5Kk5b8gAqQ4XBzFbZB/3cwbKSsEL99RKCwFnPg/GTqBDEWPTw7vv/mIrP/aLEHoCgo+RX5e7S809wgvgvtsFyw/3jXzlVtZxp8EMJCEvBU5hqyT1UNhFKvGSgaDu1jihi1CZyFJBE5iJy+r0O/wY+ckEisbcgtvG8w46hWBIR/6/CPuYxNJo6Dlt2I2PpTdMoaMiquKPh/ioV7WvdhezRHk1VTEnooIURrXtXOe+0t6RkwieNgzSk="
    on:
      tags: true
      branch: master
      python: 3.8
    skip_existing: true
    committer-from-gh: true
