name: 🚀 Deploy Documentation

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_
  workflow_dispatch:

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      # Build the book
      - name: Build the book
        run: |
          make docs
      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
